In [57]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

print("Libraries imported successfully!")

Libraries imported successfully!

In [58]:
df = pd.read_csv(r"C:\Crop Yield Prediction\data\Crop Yield Data.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (19689, 13)

In [59]:
df.head()

,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Avg_Temperature,Max_Temperature,Min_Temperature
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,2051.4,7024878.38,22882.34,0.796,23.692,33.435,14.779
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,2051.4,631643.29,2057.47,0.710,23.692,33.435,14.779
2,Castor seed,1997,Kharif,Assam,796.0,22,2051.4,75755.32,246.76,0.238,23.692,33.435,14.779
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,2051.4,1870661.52,6093.36,5238.052,23.692,33.435,14.779
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,2051.4,165500.63,539.09,0.421,23.692,33.435,14.779

In [60]:
print("Data Types:")
print(df.dtypes)

Data Types:
Crop                   str
Crop_Year            int64
Season                 str
State                  str
Area               float64
Production           int64
Annual_Rainfall    float64
Fertilizer         float64
Pesticide          float64
Yield              float64
Avg_Temperature    float64
Max_Temperature    float64
Min_Temperature    float64
dtype: object

In [61]:
missing_data = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_data

                 Missing Values  Percentage
Crop                          0    0.000000
Crop_Year                     0    0.000000
Season                        0    0.000000
State                         0    0.000000
Area                          0    0.000000
Production                    0    0.000000
Annual_Rainfall               2    0.010158
Fertilizer                    2    0.010158
Pesticide                     2    0.010158
Yield                         1    0.005079
Avg_Temperature               2    0.010158
Max_Temperature               0    0.000000
Min_Temperature               0    0.000000

In [62]:
# Handle missing values

numerical_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_columns = df.select_dtypes(
    include=["object"]
).columns

# Fill missing numerical values with median
for column in numerical_columns:
    df[column] = df[column].fillna(df[column].median())

# Fill missing categorical values with most frequent value
for column in categorical_columns:
    df[column] = df[column].fillna(df[column].mode()[0])

print("Missing values treated successfully!")
print("\nMissing values after treatment:")
print(df.isnull().sum())

Missing values treated successfully!

Missing values after treatment:
Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Yield              0
Avg_Temperature    0
Max_Temperature    0
Min_Temperature    0
dtype: int64

C:\Users\Manisha\AppData\Local\Temp\ipykernel_9660\3241948284.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

In [63]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate records:", duplicate_count)

Number of duplicate records: 0

In [64]:
# Check for duplicate records

duplicate_count = df.duplicated().sum()

print("Number of duplicate records:", duplicate_count)

if duplicate_count > 0:
    df = df.drop_duplicates().reset_index(drop=True)
    print("Duplicate records removed successfully!")
else:
    print("No duplicate records found.")

print("Dataset shape after duplicate removal:", df.shape)

Number of duplicate records: 0
No duplicate records found.
Dataset shape after duplicate removal: (19689, 13)

In [65]:
df = df.drop_duplicates().reset_index(drop=True)

print("Duplicates removed successfully!")
print("New shape:", df.shape)

Duplicates removed successfully!
New shape: (19689, 13)

In [66]:
X = df.drop("Yield", axis=1)
y = df["Yield"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (19689, 12)
Target shape: (19689,)

In [67]:
print("Input Features:")
print(X.columns.tolist())

print("\nTarget Variable:")
print("Yield")

Input Features:
['Crop', 'Crop_Year', 'Season', 'State', 'Area', 'Production', 'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Avg_Temperature', 'Max_Temperature', 'Min_Temperature']

Target Variable:
Yield

In [68]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

print("Training target shape:", y_train.shape)
print("Testing target shape:", y_test.shape)

Training data shape: (15751, 12)
Testing data shape: (3938, 12)
Training target shape: (15751,)
Testing target shape: (3938,)

In [69]:
numerical_features = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object"]
).columns.tolist()

print("Numerical Features:")
print(numerical_features)

print("\nCategorical Features:")
print(categorical_features)

Numerical Features:
['Crop_Year', 'Area', 'Production', 'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Avg_Temperature', 'Max_Temperature', 'Min_Temperature']

Categorical Features:
['Crop', 'Season', 'State']

C:\Users\Manisha\AppData\Local\Temp\ipykernel_9660\239260577.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X.select_dtypes(

In [70]:
numerical_features = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object"]
).columns.tolist()

print("Numerical Features:")
print(numerical_features)

print("\nCategorical Features:")
print(categorical_features)

C:\Users\Manisha\AppData\Local\Temp\ipykernel_9660\239260577.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X.select_dtypes(

Numerical Features:
['Crop_Year', 'Area', 'Production', 'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Avg_Temperature', 'Max_Temperature', 'Min_Temperature']

Categorical Features:
['Crop', 'Season', 'State']

In [71]:
# Numerical preprocessing

numerical_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

print("Numerical preprocessing pipeline created!")

Numerical preprocessing pipeline created!

In [72]:
categorical_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

print("Categorical preprocessing pipeline created!")

Categorical preprocessing pipeline created!

In [73]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_pipeline, numerical_features),
        ("cat", categorical_pipeline, categorical_features)
    ]
)

print("Preprocessing pipeline created successfully!")

Preprocessing pipeline created successfully!

In [74]:
preprocessor.fit(X_train)

print("Preprocessor fitted using training data only!")

Preprocessor fitted using training data only!

In [75]:
X_train_processed = preprocessor.transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Training data processed successfully!")
print("Testing data processed successfully!")

print("Processed training shape:", X_train_processed.shape)
print("Processed testing shape:", X_test_processed.shape)

Training data processed successfully!
Testing data processed successfully!
Processed training shape: (15751, 100)
Processed testing shape: (3938, 100)

In [76]:
print("Type of processed training data:", type(X_train_processed))
print("Training samples:", X_train_processed.shape[0])
print("Testing samples:", X_test_processed.shape[0])

Type of processed training data: <class 'scipy.sparse._csr.csr_matrix'>
Training samples: 15751
Testing samples: 3938

## Train-Test Split

The dataset is divided into training and testing sets using an 80:20 ratio.

The training set is used to learn the preprocessing parameters and train the machine learning models, while the testing set is kept separate for final model evaluation.

A fixed random state of 42 is used to ensure reproducibility.

In [77]:
from sklearn.model_selection import train_test_split

X = df.drop("Yield", axis=1)
y = df["Yield"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)
print("Training target shape:", y_train.shape)
print("Testing target shape:", y_test.shape)

Training data shape: (15751, 12)
Testing data shape: (3938, 12)
Training target shape: (15751,)
Testing target shape: (3938,)

In [78]:
numerical_features = X_train.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X_train.select_dtypes(
    include=["object"]
).columns.tolist()

print("Numerical Features:")
print(numerical_features)

print("\nCategorical Features:")
print(categorical_features)

Numerical Features:
['Crop_Year', 'Area', 'Production', 'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Avg_Temperature', 'Max_Temperature', 'Min_Temperature']

Categorical Features:
['Crop', 'Season', 'State']

C:\Users\Manisha\AppData\Local\Temp\ipykernel_9660\2487196616.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X_train.select_dtypes(

In [79]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

numerical_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

print("Numerical preprocessing pipeline created successfully!")
print("Steps:")
print("1. Median imputation")
print("2. StandardScaler")

Numerical preprocessing pipeline created successfully!
Steps:
1. Median imputation
2. StandardScaler

In [80]:
from sklearn.preprocessing import OneHotEncoder

categorical_pipeline = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

print("Categorical preprocessing pipeline created successfully!")
print("Steps:")
print("1. Most-frequent-value imputation")
print("2. One-hot encoding")

Categorical preprocessing pipeline created successfully!
Steps:
1. Most-frequent-value imputation
2. One-hot encoding

In [81]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_pipeline, numerical_features),
        ("cat", categorical_pipeline, categorical_features)
    ]
)

print("Combined preprocessing pipeline created successfully!")

Combined preprocessing pipeline created successfully!

In [82]:
# Fit preprocessing only on training data

preprocessor.fit(X_train)

print("Preprocessor fitted using training data only.")
print("Test data was not used to learn imputation or scaling parameters.")

Preprocessor fitted using training data only.
Test data was not used to learn imputation or scaling parameters.

In [83]:
X_train_processed = preprocessor.transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Training data processed successfully!")
print("Testing data processed successfully!")

print("\nProcessed Training Shape:", X_train_processed.shape)
print("Processed Testing Shape:", X_test_processed.shape)

Training data processed successfully!
Testing data processed successfully!

Processed Training Shape: (15751, 100)
Processed Testing Shape: (3938, 100)

In [84]:
print("========== PROCESSED DATA CHECK ==========")

print("Processed Training Shape:", X_train_processed.shape)
print("Processed Testing Shape:", X_test_processed.shape)

print("\nProcessed Data Type:")
print(type(X_train_processed))

print("\nTarget Training Shape:", y_train.shape)
print("Target Testing Shape:", y_test.shape)

========== PROCESSED DATA CHECK ==========
Processed Training Shape: (15751, 100)
Processed Testing Shape: (3938, 100)

Processed Data Type:
<class 'scipy.sparse._csr.csr_matrix'>

Target Training Shape: (15751,)
Target Testing Shape: (3938,)

In [85]:
print("========== FINAL PREPROCESSING SUMMARY ==========")

print("Original Dataset Shape:", df.shape)

print("\nTraining Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

print("\nNumerical Features:")
print(numerical_features)

print("\nCategorical Features:")
print(categorical_features)

print("\nTarget Variable:")
print("Yield")

print("\nProcessed Training Shape:")
print(X_train_processed.shape)

print("\nProcessed Testing Shape:")
print(X_test_processed.shape)

print("\nPreprocessing Methods:")
print("- Missing numerical values: Median imputation")
print("- Missing categorical values: Most frequent value")
print("- Categorical encoding: One-Hot Encoding")
print("- Numerical scaling: StandardScaler")
print("- Train-Test Split: 80:20")
print("- Random State: 42")

print("\nPreprocessing completed successfully!")

========== FINAL PREPROCESSING SUMMARY ==========
Original Dataset Shape: (19689, 13)

Training Data Shape: (15751, 12)
Testing Data Shape: (3938, 12)

Numerical Features:
['Crop_Year', 'Area', 'Production', 'Annual_Rainfall', 'Fertilizer', 'Pesticide', 'Avg_Temperature', 'Max_Temperature', 'Min_Temperature']

Categorical Features:
['Crop', 'Season', 'State']

Target Variable:
Yield

Processed Training Shape:
(15751, 100)

Processed Testing Shape:
(3938, 100)

Preprocessing Methods:
- Missing numerical values: Median imputation
- Missing categorical values: Most frequent value
- Categorical encoding: One-Hot Encoding
- Numerical scaling: StandardScaler
- Train-Test Split: 80:20
- Random State: 42

Preprocessing completed successfully!

In [86]:
# Check relationship between Production, Area and Yield

print("Correlation between Production and Yield:")
print(df["Production"].corr(df["Yield"]))

print("\nCorrelation between Area and Yield:")
print(df["Area"].corr(df["Yield"]))

print("\nProduction / Area comparison:")
comparison = pd.DataFrame({
    "Production": df["Production"],
    "Area": df["Area"],
    "Yield": df["Yield"],
    "Production_per_Area": df["Production"] / df["Area"]
})

comparison.head(10)

Correlation between Production and Yield:
0.5708085985465496

Correlation between Area and Yield:
0.0018584826305979615

Production / Area comparison:

   Production     Area     Yield  Production_per_Area
0       56708  73814.0     0.796             0.768255
1        4685   6637.0     0.710             0.705891
2          22    796.0     0.238             0.027638
3   126905000  19656.0  5238.052          6456.298331
4         794   1739.0     0.421             0.456584
5        9073  13587.0     0.644             0.667771
6        1507   2979.0     0.465             0.505874
7      904095  94520.0     9.920             9.565118
8        5158  10098.0     0.461             0.510794
9       14721  19216.0     0.616             0.766080

In [87]:
print("========== MISSING VALUE VERIFICATION ==========")

print("Missing values in X_train:")
print(X_train.isnull().sum())

print("\nMissing values in X_test:")
print(X_test.isnull().sum())

========== MISSING VALUE VERIFICATION ==========
Missing values in X_train:
Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Avg_Temperature    0
Max_Temperature    0
Min_Temperature    0
dtype: int64

Missing values in X_test:
Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Avg_Temperature    0
Max_Temperature    0
Min_Temperature    0
dtype: int64

## Preprocessing Conclusion

The Crop Yield Dataset was successfully prepared for machine learning.

Duplicate records were identified and removed where applicable. Missing numerical values were handled using median imputation, while missing categorical values were handled using the most frequent value.

Categorical variables were converted into numerical form using One-Hot Encoding. Numerical variables were standardized using StandardScaler.

The dataset was divided into training and testing sets using an 80:20 ratio.

To prevent data leakage, the preprocessing pipeline was fitted only on the training data and then applied to both the training and testing data.

The resulting processed datasets are ready for machine learning model training.

# Feature Selection

Feature selection is performed to identify the variables that are useful for predicting crop yield.

The selection process considers:
- Correlation with the target variable
- Agricultural relevance
- Data leakage
- Availability of the feature at prediction time

Features that contain target leakage will not be used for model training.

In [88]:
print("========== PRODUCTION AND YIELD RELATIONSHIP ==========")

production_yield_corr = df["Production"].corr(df["Yield"])

print("Correlation between Production and Yield:")
print(production_yield_corr)

print("\nProduction per Area:")
production_per_area = df["Production"] / df["Area"]

print(production_per_area.describe())

========== PRODUCTION AND YIELD RELATIONSHIP ==========
Correlation between Production and Yield:
0.5708085985465496

Production per Area:
count    19689.000000
mean        83.840783
std        923.597094
min          0.000000
25%          0.595850
50%          1.035673
75%          2.463386
max      21105.000000
dtype: float64

In [89]:
print("========== YIELD AND PRODUCTION/AREA CHECK ==========")

comparison = pd.DataFrame({
    "Yield": df["Yield"],
    "Production_per_Area": df["Production"] / df["Area"]
})

comparison["Difference"] = (
    comparison["Yield"] - comparison["Production_per_Area"]
)

print(comparison.head(10))

print("\nMean absolute difference:")
print(comparison["Difference"].abs().mean())

print("\nMaximum absolute difference:")
print(comparison["Difference"].abs().max())

========== YIELD AND PRODUCTION/AREA CHECK ==========
      Yield  Production_per_Area   Difference
0     0.796             0.768255     0.027745
1     0.710             0.705891     0.004109
2     0.238             0.027638     0.210362
3  5238.052          6456.298331 -1218.246331
4     0.421             0.456584    -0.035584
5     0.644             0.667771    -0.023771
6     0.465             0.505874    -0.040874
7     9.920             9.565118     0.354882
8     0.461             0.510794    -0.049794
9     0.616             0.766080    -0.150080

Mean absolute difference:
5.931012354428287

Maximum absolute difference:
3733.992814186022

In [90]:
print("========== CORRELATION WITH YIELD ==========")

yield_correlation = df.corr(
    numeric_only=True
)["Yield"].sort_values(
    ascending=False
)

yield_correlation

========== CORRELATION WITH YIELD ==========

Yield              1.000000
Production         0.570809
Min_Temperature    0.057606
Avg_Temperature    0.039344
Annual_Rainfall    0.020769
Max_Temperature    0.018742
Fertilizer         0.002862
Crop_Year          0.002539
Area               0.001858
Pesticide          0.001784
Name: Yield, dtype: float64

In [91]:
feature_selection = pd.DataFrame({
    "Feature": X.columns,
    "Data Type": X.dtypes.astype(str).values
})

feature_selection["Selected"] = "Yes"

feature_selection

            Feature Data Type Selected
0              Crop       str      Yes
1         Crop_Year     int64      Yes
2            Season       str      Yes
3             State       str      Yes
4              Area   float64      Yes
5        Production     int64      Yes
6   Annual_Rainfall   float64      Yes
7        Fertilizer   float64      Yes
8         Pesticide   float64      Yes
9   Avg_Temperature   float64      Yes
10  Max_Temperature   float64      Yes
11  Min_Temperature   float64      Yes

## Feature Selection Reasoning

The features are selected based on their relevance to crop yield prediction and their availability during prediction.

### Features considered

- Crop: identifies the crop type.
- Crop_Year: represents the agricultural year.
- Season: represents the growing season.
- State: represents geographical variation.
- Area: represents cultivated area.
- Production: checked separately for possible target leakage.
- Annual_Rainfall: represents rainfall conditions.
- Fertilizer: represents fertilizer usage.
- Pesticide: represents pesticide usage.
- Avg_Temperature: represents average temperature.
- Max_Temperature: represents maximum temperature.
- Min_Temperature: represents minimum temperature.

Production is specifically checked for target leakage because it may have a mathematical relationship with Yield and Area.